/// <reference types="node" />
/**
 * Reads src/ to describe the public API. Shared by the structural tests and
 * scripts/gen.ts so the generated catalog and the checks never disagree.
 */
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

export const ROOT = fileURLToPath(new URL("../..", import.meta.url));
export const SRC = join(ROOT, "src");

/** Folders whose files are public API, in the order they appear in docs. */
export const PUBLIC_FOLDERS = [
  "sources",
  "combiners",
  "operators",
  "sinks",
  "workers",
  "testing",
] as const;
export type PublicFolder = (typeof PUBLIC_FOLDERS)[number];

/**
 * Import layers, lowest first. A file may import only from its own layer or
 * a lower one. Root files (types.ts, errors.ts) are the foundation.
 */
export const LAYERS = [
  "foundation",
  "internal",
  "sources",
  "combiners",
  "operators",
  "sinks",
  "workers",
  "testing",
];

export interface Export {
  readonly name: string;
  readonly folder: PublicFolder;
  readonly file: string;
  readonly summary: string;
  readonly hasExample: boolean;
  readonly isFunction: boolean;
}

export function sourceFiles(folder?: string): string[] {
  const dir = folder ? join(SRC, folder) : SRC;
  return readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.endsWith(".ts"))
    .map((entry) => (folder ? `${folder}/${entry.name}` : entry.name))
    .sort();
}

export function allSourceFiles(): string[] {
  return [...sourceFiles(), ...LAYERS.slice(1).flatMap((layer) => sourceFiles(layer))];
}

export function read(file: string): string {
  return readFileSync(join(SRC, file), "utf8");
}

export function layerOf(file: string): number {
  const folder = file.includes("/") ? file.slice(0, file.indexOf("/")) : "foundation";
  return LAYERS.indexOf(folder);
}

/** Relative imports in a source file, resolved to paths under src/. */
export function importsOf(file: string): string[] {
  const dir = file.includes("/") ? file.slice(0, file.lastIndexOf("/")) : "";
  // Strip comments first so `import` lines inside JSDoc examples are ignored.
  const code = read(file)
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/^\s*\/\/.*$/gm, "");
  const specifiers = [...code.matchAll(/^(?:import|export)[^"';]*?from\s+["']([^"']+)["']/gm)].map(
    (m) => m[1] ?? "",
  );
  return specifiers.map((spec) => {
    if (!spec.startsWith(".")) return spec;
    const parts = [...(dir ? dir.split("/") : []), ...spec.split("/")];
    const out: string[] = [];
    for (const part of parts) {
      if (part === "..") out.pop();
      else if (part !== ".") out.push(part);
    }
    return out.join("/").replace(/\.js$/, ".ts");
  });
}

function summarize(doc: string): string {
  const text = doc
    .split("\n")
    .map((line) => line.replace(/^\s*\*\s?/, "").trim())
    .join("\n")
    .split(/\n\s*\n|\n@/)[0]
    ?.replace(/\s+/g, " ")
    .trim();
  const sentence = /^(.+?\.)(\s|$)/.exec(text ?? "");
  return sentence?.[1] ?? text ?? "";
}

export function publicExports(): Export[] {
  const seen = new Set<string>();
  const out: Export[] = [];
  for (const folder of PUBLIC_FOLDERS) {
    for (const file of sourceFiles(folder)) {
      if (file.endsWith("/index.ts")) continue;
      const pattern =
        /(?:\/\*\*((?:(?!\*\/)[\s\S])*)\*\/\s*)?export (?:async )?(function|const) (\w+)/g;
      for (const match of read(file).matchAll(pattern)) {
        const [, doc = "", kind, name = ""] = match;
        if (seen.has(name)) continue;
        seen.add(name);
        out.push({
          name,
          folder,
          file,
          summary: summarize(doc),
          hasExample: doc.includes("@example"),
          isFunction: kind === "function",
        });
      }
    }
  }
  return out;
}

const TITLES: Record<PublicFolder, string> = {
  sources: "Sources: create streams",
  combiners: "Combiners: many streams into one",
  operators: "Operators: use with `pipeThrough()`",
  sinks: "Sinks: consume streams",
  workers: "Workers: run stages on other threads",
  testing: "Testing: import from `pipewise/testing`",
};

/** The generated operator catalog, docs/generated/operators.md. */
export function renderCatalog(): string {
  const exports = publicExports();
  const lines = [
    "<!-- Generated by `pnpm gen` from JSDoc in src/. Do not edit. -->",
    "",
    "# API catalog",
    "",
    "Each name links to its source, where the JSDoc has full details and an example.",
  ];
  for (const folder of PUBLIC_FOLDERS) {
    lines.push("", `## ${TITLES[folder]}`, "", "| Name | Summary |", "| --- | --- |");
    for (const e of exports.filter((x) => x.folder === folder)) {
      lines.push(`| [\`${e.name}\`](../../src/${e.file}) | ${e.summary.replace(/\|/g, "\\|")} |`);
    }
  }
  return lines.join("\n") + "\n";
}

/** The expected contents of src/<folder>/index.ts. */
export function renderIndex(folder: PublicFolder): string {
  return (
    sourceFiles(folder)
      .filter((f) => !f.endsWith("/index.ts"))
      .map((f) => `export * from "./${f.slice(folder.length + 1).replace(/\.ts$/, ".js")}";`)
      .join("\n") + "\n"
  );
}
